version: '3.1'

services:

  mongo:
    image: mongo_image
    restart: always
    environment:
      MONGO_INITDB: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db:/data/db
    networks:
      - backend
  spring:
    image: spring_image
    ports:
    - 8080
    networks:
      - backend
    depends_on:
      - mongo
networks:
  backend:
